name: Deploy to Firebase

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Install @angular/cli
        run: npm i -D -E @angular/cli
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@master
        with:
          cordova-version: 8
      - name: Install app dependencies
        run: npm ci
      - name: Install functions dependencies
        run: cd functions && npm i && cd ..
      - name: Build prod app
        run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
